modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="voiddunyasi"
version="${file.jarVersion}"
displayName="Mr Void'in Dünyası"
authors="Mr Void"
description='''
Bilinmeyen maddeden oluşan, seyrek ortaçağ köyleriyle dolu sessiz bir düzlük boyutu.
Asa ile boyutlar arasında ışınlan.
'''

[[dependencies.voiddunyasi]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.voiddunyasi]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
